### PR TITLE
Improve efficiency

### PR DESCRIPTION
**Pull request by GerardSontag**

### CODE REVIEW

**Comment by GerardSontag** [comment]
Hello Attila,
Is it possible to create a bin file for the 8266 with the help of Travis C.I. ? Can you help me writing the .yml
If not, could you help me to create a tool chain, i'am completly novice with this kind of tool. 
Thank you for the work you've done creating Punnyforth.
Gérard

**Comment by zeroflag** [comment]
I don't think it can be easily done. Currently travisci makes x86 build which is just a single gcc command. But building an esp binary requires the esp sdk and esp open rtos. Maybe it can be done, but I haven't done anything similar with travisci yet.

The build instructions for making an esp binary are here: https://github.com/zeroflag/punyforth/wiki/Build-environment-setup

**Comment by GerardSontag** [comment]
Attila,
Thank you for your answer. I will try to find my way in all this unix command on bash under windows.
Gérard

**Comment by zeroflag** [comment]
Gérard,
Ok, cool. Feel free to ask any questions.
Attila

**Pull request merged**
